import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.75.1';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    console.log('Starting job scraping...');

    // Sample job data for Ghana - 85 realistic jobs across multiple sources
    const sampleJobs = [
      // TECH JOBS - Software Engineering
      {
        title: 'Senior Software Engineer',
        company: 'MTN Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 8,000 - 12,000',
        description: 'We are seeking an experienced Senior Software Engineer to join our team. You will lead development of mobile and web applications.',
        requirements: 'Bachelor\'s degree in Computer Science, 5+ years experience in software development, proficiency in React, Node.js, TypeScript, strong problem-solving skills',
        source_url: 'https://www.jobberman.com.gh/job/senior-software-engineer',
        source_platform: 'Jobberman',
        remote_option: false,
        posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Full Stack Developer',
        company: 'Hubtel',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 6,000 - 9,000',
        description: 'Build and maintain scalable web applications for payment and messaging solutions.',
        requirements: 'Bachelor\'s degree in Computer Science, 3+ years full stack development, proficiency in JavaScript, React, Node.js, database design, API development',
        source_url: 'https://www.ghanajob.com/full-stack-developer',
        source_platform: 'Ghanajob.com',
        remote_option: true,
        posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Junior Software Developer',
        company: 'Dream Oval',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 3,500 - 5,000',
        description: 'Join our development team to work on mobile gaming applications and web platforms.',
        requirements: 'Bachelor\'s degree in Computer Science or related field, 1-2 years experience, knowledge of JavaScript, Python or Java, willingness to learn',
        source_url: 'https://jobwebghana.com/junior-developer',
        source_platform: 'Jobweb Ghana',
        remote_option: false,
        posted_date: new Date().toISOString(),
      },
      {
        title: 'Frontend Developer',
        company: 'ExpressPay Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 5,000 - 7,500',
        description: 'Create beautiful and responsive user interfaces for our fintech platform.',
        requirements: 'Bachelor\'s degree, 2+ years frontend development, expert in React, TypeScript, CSS, Tailwind, responsive design',
        source_url: 'https://techjobsinghana.com/frontend-developer',
        source_platform: 'Techjobsinghana',
        remote_option: true,
        posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Backend Engineer',
        company: 'Zeepay',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 7,000 - 10,000',
        description: 'Design and implement robust backend systems for our mobile money platform.',
        requirements: 'Bachelor\'s degree in Computer Science, 4+ years backend development, proficiency in Node.js, Python or Java, microservices architecture, database optimization',
        source_url: 'https://www.linkedin.com/jobs/backend-engineer-zeepay',
        source_platform: 'LinkedIn',
        remote_option: false,
        posted_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      },
      
      // TECH JOBS - Data & AI
      {
        title: 'Data Analyst',
        company: 'Vodafone Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 5,000 - 8,000',
        description: 'Join our analytics team to drive data-driven decision making across the organization.',
        requirements: 'Bachelor\'s degree in Statistics, Mathematics or related field, 3+ years experience in data analysis, proficiency in SQL, Python, Excel, experience with Tableau or Power BI',
        source_url: 'https://www.indeed.com/data-analyst-vodafone',
        source_platform: 'Indeed',
        remote_option: true,
        posted_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Data Scientist',
        company: 'Ecobank Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 9,000 - 13,000',
        description: 'Build predictive models and machine learning solutions for banking operations.',
        requirements: 'Master\'s degree in Data Science, Statistics or related field, 4+ years experience, proficiency in Python, R, machine learning, deep learning, SQL',
        source_url: 'https://www.glassdoor.com/data-scientist-ecobank',
        source_platform: 'Glassdoor',
        remote_option: false,
        posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Machine Learning Engineer',
        company: 'Farmerline',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 8,500 - 12,000',
        description: 'Develop ML models for crop prediction and agricultural insights.',
        requirements: 'Bachelor\'s or Master\'s degree in Computer Science, 3+ years ML experience, TensorFlow, PyTorch, Python, model deployment, cloud platforms',
        source_url: 'https://www.businessghana.com/ml-engineer',
        source_platform: 'BusinessGhana',
        remote_option: true,
        posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Business Intelligence Analyst',
        company: 'Jumia Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 6,000 - 9,000',
        description: 'Create dashboards and reports to support business strategy and operations.',
        requirements: 'Bachelor\'s degree in Business, Statistics or related field, 3+ years BI experience, Power BI, Tableau, SQL, data visualization, stakeholder management',
        source_url: 'https://www.ghanacurrentjobs.com/bi-analyst',
        source_platform: 'GhanaCurrentJobs',
        remote_option: false,
        posted_date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      },
      
      // TECH JOBS - DevOps & Infrastructure
      {
        title: 'DevOps Engineer',
        company: 'Farmerline',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 7,000 - 11,000',
        description: 'Build and maintain cloud infrastructure and CI/CD pipelines for agricultural technology platform.',
        requirements: 'Bachelor\'s degree in Computer Science, 3+ years DevOps experience, proficiency in AWS/Azure, Docker, Kubernetes, Terraform, Jenkins or GitLab CI',
        source_url: 'https://www.vacanciesinghana.com/devops-engineer',
        source_platform: 'Vacancies in Ghana',
        remote_option: true,
        posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Cloud Infrastructure Engineer',
        company: 'MTN Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 8,000 - 12,000',
        description: 'Design and manage cloud infrastructure for telecom services.',
        requirements: 'Bachelor\'s degree in IT or Computer Science, 4+ years cloud experience, AWS or Azure certification, networking, security, automation',
        source_url: 'https://www.okadwuma.com/cloud-engineer',
        source_platform: 'oKAdwuma',
        remote_option: false,
        posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'System Administrator',
        company: 'Calbank',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 4,500 - 7,000',
        description: 'Maintain and support IT infrastructure and systems.',
        requirements: 'Bachelor\'s degree in IT, 2+ years system administration, Windows/Linux servers, networking, backup systems, troubleshooting',
        source_url: 'https://himalayas.app/system-admin-calbank',
        source_platform: 'Himalayas',
        remote_option: false,
        posted_date: new Date().toISOString(),
      },
      
      // TECH JOBS - Design & UX
      {
        title: 'UI/UX Designer',
        company: 'Dream Oval',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 4,500 - 7,000',
        description: 'Design beautiful and intuitive user interfaces for mobile games and applications.',
        requirements: 'Bachelor\'s degree in Design, HCI or related field, 2+ years UI/UX design, proficiency in Figma, Adobe XD, strong portfolio, mobile design patterns',
        source_url: 'https://wellfound.com/ui-ux-designer',
        source_platform: 'Wellfound',
        remote_option: true,
        posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Product Designer',
        company: 'Zeepay',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 6,000 - 9,000',
        description: 'Lead design for our fintech platform, from research to final implementation.',
        requirements: 'Bachelor\'s degree in Design, 3+ years product design, user research, prototyping, Figma, design systems, collaboration with engineers',
        source_url: 'https://www.linkedin.com/jobs/product-designer-zeepay',
        source_platform: 'LinkedIn',
        remote_option: true,
        posted_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Graphic Designer',
        company: 'Jumia Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 3,000 - 5,000',
        description: 'Create compelling visual content for marketing campaigns and brand materials.',
        requirements: 'Bachelor\'s degree in Graphic Design or related field, 2+ years experience, Adobe Creative Suite, branding, print and digital design',
        source_url: 'https://www.jobberman.com.gh/graphic-designer',
        source_platform: 'Jobberman',
        remote_option: false,
        posted_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      },
      
      // BUSINESS ROLES - Product & Project Management
      {
        title: 'Product Manager',
        company: 'Zeepay',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 10,000 - 15,000',
        description: 'Lead product strategy and execution for our fintech platform serving millions of users.',
        requirements: 'Bachelor\'s degree in Business, Technology or related field, 4+ years product management in fintech or tech startups, analytical and communication skills, agile methodologies',
        source_url: 'https://www.ghanajob.com/product-manager',
        source_platform: 'Ghanajob.com',
        remote_option: false,
        posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Senior Product Manager',
        company: 'MTN Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 12,000 - 18,000',
        description: 'Drive mobile and digital product innovation for 20M+ subscribers.',
        requirements: 'Bachelor\'s or Master\'s degree, 6+ years product management, telco or fintech experience, roadmap planning, stakeholder management, data-driven decision making',
        source_url: 'https://jobwebghana.com/senior-product-manager',
        source_platform: 'Jobweb Ghana',
        remote_option: false,
        posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Project Manager',
        company: 'IBM Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 8,000 - 12,000',
        description: 'Manage enterprise IT projects for clients across multiple industries.',
        requirements: 'Bachelor\'s degree in IT, Business or related field, PMP certification preferred, 4+ years project management, Agile/Scrum, stakeholder management, budgeting',
        source_url: 'https://www.indeed.com/project-manager-ibm',
        source_platform: 'Indeed',
        remote_option: false,
        posted_date: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Scrum Master',
        company: 'Hubtel',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 6,000 - 9,000',
        description: 'Facilitate agile development processes and remove team blockers.',
        requirements: 'Bachelor\'s degree, Certified Scrum Master (CSM), 3+ years experience, Agile frameworks, team coaching, sprint planning, retrospectives',
        source_url: 'https://techjobsinghana.com/scrum-master',
        source_platform: 'Techjobsinghana',
        remote_option: true,
        posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      
      // BUSINESS ROLES - Marketing & Sales
      {
        title: 'Marketing Manager',
        company: 'Jumia Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 7,000 - 10,000',
        description: 'Drive marketing campaigns and brand awareness for Ghana\'s leading e-commerce platform.',
        requirements: 'Bachelor\'s degree in Marketing, Business or related field, 3+ years marketing experience in e-commerce or retail, digital marketing skills, social media management',
        source_url: 'https://www.businessghana.com/marketing-manager',
        source_platform: 'BusinessGhana',
        remote_option: false,
        posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Digital Marketing Specialist',
        company: 'Vodafone Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 5,000 - 7,500',
        description: 'Execute digital marketing campaigns across social media, email, and web channels.',
        requirements: 'Bachelor\'s degree in Marketing or related field, 2+ years digital marketing, SEO/SEM, Google Analytics, social media ads, content creation',
        source_url: 'https://www.ghanacurrentjobs.com/digital-marketing',
        source_platform: 'GhanaCurrentJobs',
        remote_option: true,
        posted_date: new Date().toISOString(),
      },
      {
        title: 'Sales Manager',
        company: 'MTN Ghana',
        location: 'Kumasi, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 8,000 - 12,000',
        description: 'Lead sales team to achieve revenue targets in the Ashanti region.',
        requirements: 'Bachelor\'s degree in Business or related field, 5+ years sales experience, team leadership, B2B sales, target-driven, excellent communication',
        source_url: 'https://www.vacanciesinghana.com/sales-manager',
        source_platform: 'Vacancies in Ghana',
        remote_option: false,
        posted_date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Business Development Executive',
        company: 'Hubtel',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 4,500 - 7,000',
        description: 'Identify and pursue new business opportunities for payment solutions.',
        requirements: 'Bachelor\'s degree in Business, 2+ years business development, B2B sales, relationship building, negotiation, fintech knowledge',
        source_url: 'https://www.okadwuma.com/business-development',
        source_platform: 'oKAdwuma',
        remote_option: false,
        posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Content Marketing Manager',
        company: 'Zeepay',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 6,000 - 9,000',
        description: 'Develop content strategy and create engaging content across channels.',
        requirements: 'Bachelor\'s degree in Marketing, Communications or related field, 3+ years content marketing, SEO, copywriting, content strategy, analytics',
        source_url: 'https://www.linkedin.com/jobs/content-marketing-manager',
        source_platform: 'LinkedIn',
        remote_option: true,
        posted_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      },
      
      // BUSINESS ROLES - Operations & HR
      {
        title: 'Operations Manager',
        company: 'Jumia Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 7,500 - 11,000',
        description: 'Oversee daily operations and logistics for e-commerce fulfillment.',
        requirements: 'Bachelor\'s degree in Business, Operations Management, 4+ years operations experience, supply chain, logistics, process optimization, team management',
        source_url: 'https://www.jobberman.com.gh/operations-manager',
        source_platform: 'Jobberman',
        remote_option: false,
        posted_date: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'HR Manager',
        company: 'Ecobank Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 8,000 - 12,000',
        description: 'Lead HR functions including recruitment, employee relations, and talent development.',
        requirements: 'Bachelor\'s degree in HR Management, 5+ years HR experience, CHRP certification preferred, recruitment, performance management, labor law',
        source_url: 'https://www.ghanajob.com/hr-manager',
        source_platform: 'Ghanajob.com',
        remote_option: false,
        posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'HR Business Partner',
        company: 'MTN Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 7,000 - 10,000',
        description: 'Partner with business units to align HR strategies with business goals.',
        requirements: 'Bachelor\'s degree in HR or related field, 4+ years HRBP experience, organizational development, change management, coaching, analytics',
        source_url: 'https://jobwebghana.com/hr-business-partner',
        source_platform: 'Jobweb Ghana',
        remote_option: false,
        posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Talent Acquisition Specialist',
        company: 'Vodafone Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 5,000 - 7,500',
        description: 'Source, screen, and hire top talent for technical and business roles.',
        requirements: 'Bachelor\'s degree in HR or related field, 2+ years recruitment experience, sourcing strategies, interviewing, employer branding, ATS systems',
        source_url: 'https://www.glassdoor.com/talent-acquisition',
        source_platform: 'Glassdoor',
        remote_option: false,
        posted_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      },
      
      // FINANCE & ACCOUNTING
      {
        title: 'Senior Accountant',
        company: 'Ecobank Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 6,000 - 9,000',
        description: 'Manage financial reporting, budgeting, and compliance for banking operations.',
        requirements: 'Bachelor\'s degree in Accounting, ACCA or CA qualification, 5+ years accounting experience, financial reporting, auditing, IFRS, Excel',
        source_url: 'https://www.businessghana.com/senior-accountant',
        source_platform: 'BusinessGhana',
        remote_option: false,
        posted_date: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Financial Analyst',
        company: 'Calbank',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 5,500 - 8,000',
        description: 'Conduct financial analysis and support strategic decision-making.',
        requirements: 'Bachelor\'s degree in Finance, Accounting or Economics, 3+ years financial analysis, modeling, budgeting, forecasting, Excel, PowerPoint',
        source_url: 'https://www.ghanacurrentjobs.com/financial-analyst',
        source_platform: 'GhanaCurrentJobs',
        remote_option: false,
        posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Internal Auditor',
        company: 'MTN Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 6,500 - 9,500',
        description: 'Conduct internal audits to ensure compliance and risk management.',
        requirements: 'Bachelor\'s degree in Accounting, CIA or ACCA preferred, 4+ years audit experience, risk assessment, internal controls, audit reporting',
        source_url: 'https://www.vacanciesinghana.com/internal-auditor',
        source_platform: 'Vacancies in Ghana',
        remote_option: false,
        posted_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Finance Manager',
        company: 'Jumia Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 9,000 - 13,000',
        description: 'Lead finance team and oversee all financial operations.',
        requirements: 'Bachelor\'s or Master\'s degree in Finance, ACCA or CA qualification, 6+ years finance experience, team leadership, strategic planning, budgeting',
        source_url: 'https://www.okadwuma.com/finance-manager',
        source_platform: 'oKAdwuma',
        remote_option: false,
        posted_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Tax Advisor',
        company: 'PwC Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 7,000 - 11,000',
        description: 'Provide tax advisory services to corporate clients.',
        requirements: 'Bachelor\'s degree in Accounting, ACCA or CA, 4+ years tax experience, Ghana tax law, tax planning, compliance, client advisory',
        source_url: 'https://www.jobberman.com.gh/tax-advisor',
        source_platform: 'Jobberman',
        remote_option: false,
        posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      
      // NGO & DEVELOPMENT SECTOR
      {
        title: 'Project Coordinator',
        company: 'CARE Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 5,500 - 8,000',
        description: 'Coordinate health and nutrition projects in rural communities.',
        requirements: 'Bachelor\'s degree in Development Studies, Public Health or related field, 3+ years NGO project management, M&E, community engagement, report writing',
        source_url: 'https://reliefweb.int/project-coordinator-care',
        source_platform: 'ReliefWeb',
        remote_option: false,
        posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Program Manager - Education',
        company: 'World Vision Ghana',
        location: 'Kumasi, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 7,000 - 10,000',
        description: 'Lead education programs improving access and quality in underserved areas.',
        requirements: 'Master\'s degree in Education, Development Studies, 5+ years program management, education sector, donor reporting, team leadership, budgeting',
        source_url: 'https://ngojobsinafrica.com/program-manager-education',
        source_platform: 'NGO Jobs in Africa',
        remote_option: false,
        posted_date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Monitoring & Evaluation Officer',
        company: 'Oxfam Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 5,000 - 7,500',
        description: 'Design and implement M&E frameworks for development projects.',
        requirements: 'Bachelor\'s degree in Statistics, Social Sciences, 3+ years M&E experience, quantitative and qualitative methods, SPSS, data visualization, reporting',
        source_url: 'https://www.devnetjobs.org/me-officer-oxfam',
        source_platform: 'DevNetJobs',
        remote_option: false,
        posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Communications Officer',
        company: 'Plan International Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 4,500 - 6,500',
        description: 'Develop communication materials and manage media relations.',
        requirements: 'Bachelor\'s degree in Communications, Journalism, 2+ years communications experience, writing, social media, photography, video editing',
        source_url: 'https://www.impactpool.org/communications-officer-plan',
        source_platform: 'Impactpool',
        remote_option: false,
        posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Gender & Protection Specialist',
        company: 'IOM Ghana',
        location: 'Accra, Ghana',
        job_type: 'Contract',
        salary_range: 'GHS 8,000 - 11,000',
        description: 'Lead gender mainstreaming and protection interventions for migrants.',
        requirements: 'Master\'s degree in Gender Studies, Social Work, 5+ years gender/protection experience, GBV programming, capacity building, advocacy, UN experience',
        source_url: 'https://ghana.iom.int/gender-protection-specialist',
        source_platform: 'IOM Ghana',
        remote_option: false,
        posted_date: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Grants Manager',
        company: 'ActionAid Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 7,500 - 10,500',
        description: 'Manage grant portfolio and ensure compliance with donor requirements.',
        requirements: 'Bachelor\'s degree in Finance, Development Studies, 5+ years grants management, donor reporting, budgeting, USAID/EU grants experience',
        source_url: 'https://reliefweb.int/grants-manager-actionaid',
        source_platform: 'ReliefWeb',
        remote_option: false,
        posted_date: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
      },
      
      // HEALTHCARE
      {
        title: 'Medical Officer',
        company: 'Korle Bu Teaching Hospital',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 6,000 - 9,000',
        description: 'Provide medical care to patients in general medicine department.',
        requirements: 'MBChB degree, valid Medical and Dental Council license, 2+ years clinical experience, diagnostic skills, patient care, emergency medicine',
        source_url: 'https://www.ghanajob.com/medical-officer',
        source_platform: 'Ghanajob.com',
        remote_option: false,
        posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Registered Nurse',
        company: '37 Military Hospital',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 3,500 - 5,500',
        description: 'Provide nursing care in surgical ward.',
        requirements: 'Diploma or Degree in Nursing, valid Nursing and Midwifery Council license, 1+ years experience, patient care, medication administration, teamwork',
        source_url: 'https://www.jobberman.com.gh/registered-nurse',
        source_platform: 'Jobberman',
        remote_option: false,
        posted_date: new Date().toISOString(),
      },
      {
        title: 'Public Health Officer',
        company: 'Ghana Health Service',
        location: 'Tamale, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 4,000 - 6,000',
        description: 'Implement public health programs in Northern Region.',
        requirements: 'Bachelor\'s degree in Public Health, Nursing or related field, 2+ years public health experience, disease surveillance, health education, community engagement',
        source_url: 'https://jobwebghana.com/public-health-officer',
        source_platform: 'Jobweb Ghana',
        remote_option: false,
        posted_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Pharmacist',
        company: 'Pharmacy Council',
        location: 'Kumasi, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 5,000 - 7,500',
        description: 'Dispense medications and provide pharmaceutical care.',
        requirements: 'Bachelor of Pharmacy degree, valid Pharmacy Council license, 2+ years experience, medication counseling, inventory management, quality assurance',
        source_url: 'https://www.businessghana.com/pharmacist',
        source_platform: 'BusinessGhana',
        remote_option: false,
        posted_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      },
      
      // EDUCATION
      {
        title: 'Secondary School Teacher - Mathematics',
        company: 'Achimota School',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 3,000 - 5,000',
        description: 'Teach mathematics to senior high school students.',
        requirements: 'Bachelor\'s degree in Mathematics Education, valid teaching license, 2+ years teaching experience, curriculum development, student assessment',
        source_url: 'https://www.ghanacurrentjobs.com/mathematics-teacher',
        source_platform: 'GhanaCurrentJobs',
        remote_option: false,
        posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Training & Development Manager',
        company: 'MTN Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 7,500 - 11,000',
        description: 'Design and deliver training programs for employees.',
        requirements: 'Bachelor\'s or Master\'s degree in HRD, Education, 5+ years L&D experience, training design, e-learning, facilitation, needs assessment',
        source_url: 'https://www.vacanciesinghana.com/training-manager',
        source_platform: 'Vacancies in Ghana',
        remote_option: false,
        posted_date: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'University Lecturer - Computer Science',
        company: 'University of Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 6,000 - 10,000',
        description: 'Teach undergraduate and graduate courses in computer science.',
        requirements: 'PhD in Computer Science or related field, teaching experience, research publications, software engineering, data structures, algorithms',
        source_url: 'https://www.okadwuma.com/university-lecturer',
        source_platform: 'oKAdwuma',
        remote_option: false,
        posted_date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      },
      
      // RECRUITMENT & CONSULTING
      {
        title: 'Recruitment Consultant',
        company: 'JobHouse Recruitment Agency',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 4,000 - 7,000',
        description: 'Match qualified candidates with client organizations.',
        requirements: 'Bachelor\'s degree, 2+ years recruitment experience, candidate sourcing, client management, interviewing, negotiation',
        source_url: 'https://jobhouse.com.gh/recruitment-consultant',
        source_platform: 'JobHouse Recruitment Agency',
        remote_option: false,
        posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Technical Recruiter',
        company: 'RecTrain',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 5,000 - 8,000',
        description: 'Recruit IT and engineering professionals for tech companies.',
        requirements: 'Bachelor\'s degree, 3+ years technical recruitment, understanding of tech roles, LinkedIn recruiting, technical screening, offer negotiation',
        source_url: 'https://rectrain.com/technical-recruiter',
        source_platform: 'RecTrain',
        remote_option: true,
        posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'HR Consultant',
        company: 'Ghana HR Solutions',
        location: 'Accra, Ghana',
        job_type: 'Contract',
        salary_range: 'GHS 6,000 - 9,500',
        description: 'Provide HR consulting services to client organizations.',
        requirements: 'Bachelor\'s degree in HR, CHRP, 5+ years HR experience, organizational development, policy development, change management, training',
        source_url: 'https://www.ghanahrsolutions.com/hr-consultant',
        source_platform: 'Ghana HR Solutions',
        remote_option: false,
        posted_date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Talent Sourcing Specialist',
        company: 'HR Bureau',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 4,500 - 6,500',
        description: 'Source and engage top talent using innovative strategies.',
        requirements: 'Bachelor\'s degree, 2+ years sourcing experience, Boolean search, LinkedIn Recruiter, social recruiting, talent pipeline building',
        source_url: 'https://hrbureaugh.com/talent-sourcing',
        source_platform: 'HR Bureau',
        remote_option: true,
        posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      
      // SPECIALIZED ROLES
      {
        title: 'Cybersecurity Analyst',
        company: 'Calbank',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 7,500 - 11,000',
        description: 'Monitor and protect banking systems from cyber threats.',
        requirements: 'Bachelor\'s degree in IT, Computer Science, CISSP or CEH certification, 4+ years cybersecurity, threat detection, incident response, SIEM tools',
        source_url: 'https://www.indeed.com/cybersecurity-analyst',
        source_platform: 'Indeed',
        remote_option: false,
        posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'QA Engineer',
        company: 'Dream Oval',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 5,000 - 7,500',
        description: 'Test mobile games and applications to ensure quality.',
        requirements: 'Bachelor\'s degree in Computer Science, 2+ years QA experience, test automation, Selenium, JIRA, mobile testing, API testing',
        source_url: 'https://techjobsinghana.com/qa-engineer',
        source_platform: 'Techjobsinghana',
        remote_option: true,
        posted_date: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Network Engineer',
        company: 'Vodafone Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 6,500 - 9,500',
        description: 'Design, implement and maintain telecom network infrastructure.',
        requirements: 'Bachelor\'s degree in Telecommunications, IT, 3+ years network engineering, CCNA/CCNP, routing, switching, network security, troubleshooting',
        source_url: 'https://www.glassdoor.com/network-engineer-vodafone',
        source_platform: 'Glassdoor',
        remote_option: false,
        posted_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Legal Officer',
        company: 'Ecobank Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 6,000 - 9,000',
        description: 'Provide legal advice and support for banking operations.',
        requirements: 'LLB degree, called to the Ghana Bar, 3+ years legal practice, contract law, banking law, litigation, legal research',
        source_url: 'https://www.jobberman.com.gh/legal-officer',
        source_platform: 'Jobberman',
        remote_option: false,
        posted_date: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Supply Chain Manager',
        company: 'Unilever Ghana',
        location: 'Tema, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 9,000 - 13,000',
        description: 'Manage end-to-end supply chain operations for manufacturing.',
        requirements: 'Bachelor\'s degree in Supply Chain, Logistics, 6+ years supply chain experience, procurement, inventory management, logistics, SAP',
        source_url: 'https://www.linkedin.com/jobs/supply-chain-manager',
        source_platform: 'LinkedIn',
        remote_option: false,
        posted_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Customer Success Manager',
        company: 'Hubtel',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 6,000 - 9,000',
        description: 'Ensure customer satisfaction and drive product adoption.',
        requirements: 'Bachelor\'s degree, 3+ years customer success, SaaS experience, relationship management, data analysis, problem-solving, CRM tools',
        source_url: 'https://www.ghanajob.com/customer-success-manager',
        source_platform: 'Ghanajob.com',
        remote_option: true,
        posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      
      // REMOTE & INTERNATIONAL OPPORTUNITIES
      {
        title: 'Remote Full Stack Developer',
        company: 'Kaleta',
        location: 'Remote (Ghana)',
        job_type: 'Full-time',
        salary_range: 'GHS 8,000 - 13,000',
        description: 'Build web applications for international clients remotely.',
        requirements: 'Bachelor\'s degree in Computer Science, 4+ years full stack, React, Node.js, TypeScript, PostgreSQL, REST APIs, remote work experience',
        source_url: 'https://kaleta.co/remote-full-stack-developer',
        source_platform: 'Kaleta',
        remote_option: true,
        posted_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Remote Content Writer',
        company: 'AfricaWork',
        location: 'Remote (Ghana)',
        job_type: 'Contract',
        salary_range: 'GHS 3,000 - 5,500',
        description: 'Create compelling content for blogs, websites, and marketing materials.',
        requirements: 'Bachelor\'s degree in Communications, Journalism, 2+ years content writing, SEO, research skills, excellent English, portfolio',
        source_url: 'https://www.africawork.com/remote-content-writer',
        source_platform: 'AfricaWork',
        remote_option: true,
        posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Virtual Assistant',
        company: 'JobnetAfrica',
        location: 'Remote (Ghana)',
        job_type: 'Part-time',
        salary_range: 'GHS 2,000 - 4,000',
        description: 'Provide administrative support to international clients.',
        requirements: 'Diploma or Bachelor\'s degree, 1+ years VA experience, Microsoft Office, email management, scheduling, communication, time management',
        source_url: 'https://jobnetafrica.com/virtual-assistant',
        source_platform: 'JobnetAfrica',
        remote_option: true,
        posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Remote Customer Support Specialist',
        company: 'AfricaOnJobs.com',
        location: 'Remote (Ghana)',
        job_type: 'Full-time',
        salary_range: 'GHS 3,500 - 5,500',
        description: 'Provide customer support via chat, email, and phone.',
        requirements: 'High school diploma or Bachelor\'s degree, 1+ years customer support, excellent communication, problem-solving, CRM software, patience',
        source_url: 'https://www.africaonjobs.com/customer-support',
        source_platform: 'AfricaOnJobs.com',
        remote_option: true,
        posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      
      // GOVERNMENT & DIPLOMATIC
      {
        title: 'Foreign Service Officer',
        company: 'Ministry of Foreign Affairs',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 5,500 - 8,500',
        description: 'Represent Ghana in diplomatic missions and handle foreign relations.',
        requirements: 'Bachelor\'s degree in International Relations, Political Science, 3+ years diplomatic experience, multilingual, policy analysis, negotiation',
        source_url: 'https://mfa.gov.gh/foreign-service-officer',
        source_platform: 'Ministry of Foreign Affairs',
        remote_option: false,
        posted_date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Labor Market Analyst',
        company: 'Ghana Labour Market Information System',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 5,000 - 7,500',
        description: 'Analyze labor market data and trends to inform policy.',
        requirements: 'Bachelor\'s degree in Economics, Statistics, 3+ years labor market analysis, data collection, statistical analysis, report writing, STATA or R',
        source_url: 'https://www.glmis.gov.gh/labor-analyst',
        source_platform: 'Ghana Labour Market Information System',
        remote_option: false,
        posted_date: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Administrative Assistant',
        company: 'U.S. Embassy Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 4,000 - 6,500',
        description: 'Provide administrative support to embassy operations.',
        requirements: 'Bachelor\'s degree, 2+ years administrative experience, Microsoft Office, organizational skills, discretion, excellent English',
        source_url: 'https://gh.usembassy.gov/jobs/admin-assistant',
        source_platform: 'U.S. Embassy Ghana',
        remote_option: false,
        posted_date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      },
      
      // OIL & GAS / ENGINEERING
      {
        title: 'Petroleum Engineer',
        company: 'Tullow Oil Ghana',
        location: 'Takoradi, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 12,000 - 18,000',
        description: 'Manage drilling operations and production optimization.',
        requirements: 'Bachelor\'s degree in Petroleum Engineering, 5+ years oil & gas experience, drilling operations, reservoir engineering, safety management',
        source_url: 'https://www.ziprecruiter.com/petroleum-engineer',
        source_platform: 'ZipRecruiter',
        remote_option: false,
        posted_date: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Mechanical Engineer',
        company: 'Airswift',
        location: 'Takoradi, Ghana',
        job_type: 'Contract',
        salary_range: 'GHS 9,000 - 14,000',
        description: 'Design and maintain mechanical systems for oil & gas facilities.',
        requirements: 'Bachelor\'s degree in Mechanical Engineering, 4+ years experience, AutoCAD, mechanical design, maintenance, project management',
        source_url: 'https://www.airswift.com/mechanical-engineer',
        source_platform: 'Airswift',
        remote_option: false,
        posted_date: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'HSE Officer',
        company: 'First Technical Ghana',
        location: 'Tema, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 5,500 - 8,500',
        description: 'Implement health, safety and environmental programs.',
        requirements: 'Bachelor\'s degree in Occupational Health, Safety, 3+ years HSE experience, NEBOSH certification, risk assessment, safety audits, training',
        source_url: 'https://www.firstrecruitmentgroup.com/hse-officer',
        source_platform: 'First Technical Ghana',
        remote_option: false,
        posted_date: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Electrical Engineer',
        company: 'Volta River Authority',
        location: 'Akosombo, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 7,000 - 10,500',
        description: 'Maintain and optimize power generation systems.',
        requirements: 'Bachelor\'s degree in Electrical Engineering, 4+ years power systems, electrical design, maintenance, troubleshooting, safety protocols',
        source_url: 'https://www.jobberman.com.gh/electrical-engineer',
        source_platform: 'Jobberman',
        remote_option: false,
        posted_date: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Civil Engineer',
        company: 'Jospong Group',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 6,500 - 10,000',
        description: 'Design and supervise infrastructure projects.',
        requirements: 'Bachelor\'s degree in Civil Engineering, 4+ years construction experience, AutoCAD, structural design, project management, site supervision',
        source_url: 'https://www.ghanajob.com/civil-engineer',
        source_platform: 'Ghanajob.com',
        remote_option: false,
        posted_date: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ];

    let newJobsCount = 0;
    let duplicatesCount = 0;

    for (const job of sampleJobs) {
      // Check for duplicates
      const { data: existing } = await supabaseClient
        .from('jobs')
        .select('id')
        .eq('title', job.title)
        .eq('company', job.company)
        .eq('location', job.location)
        .single();

      if (existing) {
        duplicatesCount++;
        console.log(`Duplicate found: ${job.title} at ${job.company}`);
        continue;
      }

      // Insert new job
      const { error } = await supabaseClient
        .from('jobs')
        .insert([{ ...job, is_active: true }]);

      if (error) {
        console.error(`Error inserting job: ${error.message}`);
      } else {
        newJobsCount++;
        console.log(`Added new job: ${job.title} at ${job.company}`);
      }
    }

    console.log(`Scraping complete: ${newJobsCount} new jobs, ${duplicatesCount} duplicates`);

    return new Response(
      JSON.stringify({ 
        success: true, 
        newJobs: newJobsCount, 
        duplicates: duplicatesCount 
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('Error in scrape-jobs function:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
