import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.75.1';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    console.log('Starting job scraping...');

    // Sample job data - Ghana local jobs + International jobs with visa sponsorship
    const sampleJobs = [
      // ==================== GHANA LOCAL JOBS ====================
      // TECH JOBS - Software Engineering
      {
        title: 'Senior Software Engineer',
        company: 'MTN Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 8,000 - 12,000',
        description: 'We are seeking an experienced Senior Software Engineer to join our team. You will lead development of mobile and web applications.',
        requirements: 'Bachelor\'s degree in Computer Science, 5+ years experience in software development, proficiency in React, Node.js, TypeScript, strong problem-solving skills',
        source_url: 'https://www.jobberman.com.gh/job/senior-software-engineer',
        source_platform: 'Jobberman',
        remote_option: false,
        visa_sponsorship: false,
        posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Full Stack Developer',
        company: 'Hubtel',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 6,000 - 9,000',
        description: 'Build and maintain scalable web applications for payment and messaging solutions.',
        requirements: 'Bachelor\'s degree in Computer Science, 3+ years full stack development, proficiency in JavaScript, React, Node.js, database design, API development',
        source_url: 'https://www.ghanajob.com/full-stack-developer',
        source_platform: 'Ghanajob.com',
        remote_option: true,
        visa_sponsorship: false,
        posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Junior Software Developer',
        company: 'Dream Oval',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 3,500 - 5,000',
        description: 'Join our development team to work on mobile gaming applications and web platforms.',
        requirements: 'Bachelor\'s degree in Computer Science or related field, 1-2 years experience, knowledge of JavaScript, Python or Java, willingness to learn',
        source_url: 'https://jobwebghana.com/junior-developer',
        source_platform: 'Jobweb Ghana',
        remote_option: false,
        visa_sponsorship: false,
        posted_date: new Date().toISOString(),
      },
      {
        title: 'Data Analyst',
        company: 'Vodafone Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 5,000 - 8,000',
        description: 'Join our analytics team to drive data-driven decision making across the organization.',
        requirements: 'Bachelor\'s degree in Statistics, Mathematics or related field, 3+ years experience in data analysis, proficiency in SQL, Python, Excel, experience with Tableau or Power BI',
        source_url: 'https://www.indeed.com/data-analyst-vodafone',
        source_platform: 'Indeed',
        remote_option: true,
        visa_sponsorship: false,
        posted_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Product Manager',
        company: 'Zeepay',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 10,000 - 15,000',
        description: 'Lead product strategy and execution for our fintech platform serving millions of users.',
        requirements: 'Bachelor\'s degree in Business, Technology or related field, 4+ years product management in fintech or tech startups, analytical and communication skills, agile methodologies',
        source_url: 'https://www.ghanajob.com/product-manager',
        source_platform: 'Ghanajob.com',
        remote_option: false,
        visa_sponsorship: false,
        posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Marketing Manager',
        company: 'Jumia Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 7,000 - 10,000',
        description: 'Drive marketing campaigns and brand awareness for Ghana\'s leading e-commerce platform.',
        requirements: 'Bachelor\'s degree in Marketing, Business or related field, 3+ years marketing experience in e-commerce or retail, digital marketing skills, social media management',
        source_url: 'https://www.businessghana.com/marketing-manager',
        source_platform: 'BusinessGhana',
        remote_option: false,
        visa_sponsorship: false,
        posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Accountant',
        company: 'Ecobank Ghana',
        location: 'Accra, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 4,500 - 7,000',
        description: 'Manage financial records, prepare reports, and ensure compliance with banking regulations.',
        requirements: 'Bachelor\'s degree in Accounting, ACCA or CPA certification, 3+ years banking experience, proficiency in accounting software',
        source_url: 'https://www.jobberman.com.gh/accountant',
        source_platform: 'Jobberman',
        remote_option: false,
        visa_sponsorship: false,
        posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Project Coordinator',
        company: 'World Vision Ghana',
        location: 'Tamale, Ghana',
        job_type: 'Full-time',
        salary_range: 'GHS 5,500 - 8,000',
        description: 'Coordinate community development projects and manage stakeholder relationships.',
        requirements: 'Bachelor\'s degree in Development Studies, Project Management, 3+ years NGO experience, M&E skills, community engagement',
        source_url: 'https://www.ghanacurrentjobs.com/project-coordinator',
        source_platform: 'GhanaCurrentJobs',
        remote_option: false,
        visa_sponsorship: false,
        posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      },

      // ==================== UK JOBS WITH VISA SPONSORSHIP ====================
      {
        title: 'Senior Software Engineer',
        company: 'Google UK',
        location: 'London, United Kingdom',
        job_type: 'Full-time',
        salary_range: '£70,000 - £100,000',
        description: 'Join Google\'s London engineering team to build products used by billions. Work on challenging technical problems at scale with world-class engineers.',
        requirements: 'Bachelor\'s or Master\'s in Computer Science, 5+ years software development, expertise in Java, Python, or Go, distributed systems experience, strong algorithmic skills',
        source_url: 'https://careers.google.com/senior-software-engineer-london',
        source_platform: 'Google Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Data Scientist',
        company: 'HSBC',
        location: 'London, United Kingdom',
        job_type: 'Full-time',
        salary_range: '£55,000 - £80,000',
        description: 'Build machine learning models for fraud detection and customer analytics. Work with petabytes of financial data.',
        requirements: 'Master\'s or PhD in Data Science, Statistics, or related field, 3+ years experience, Python, R, SQL, machine learning, financial services experience preferred',
        source_url: 'https://www.hsbc.com/careers/data-scientist',
        source_platform: 'HSBC Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Registered Nurse - NHS',
        company: 'NHS England',
        location: 'Manchester, United Kingdom',
        job_type: 'Full-time',
        salary_range: '£28,000 - £42,000',
        description: 'Join the NHS as a Registered Nurse. Visa sponsorship and relocation support provided for qualified international nurses.',
        requirements: 'Nursing degree, NMC registration (or eligibility), IELTS/OET scores, 2+ years clinical experience, compassionate care orientation',
        source_url: 'https://www.jobs.nhs.uk/registered-nurse',
        source_platform: 'NHS Jobs',
        remote_option: false,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'DevOps Engineer',
        company: 'Barclays',
        location: 'London, United Kingdom',
        job_type: 'Full-time',
        salary_range: '£60,000 - £85,000',
        description: 'Build and maintain cloud infrastructure for one of the world\'s largest banks. Skilled Worker visa sponsorship available.',
        requirements: 'Bachelor\'s in Computer Science or related field, 4+ years DevOps experience, AWS/Azure, Kubernetes, Docker, Terraform, CI/CD pipelines',
        source_url: 'https://jobs.barclays.co.uk/devops-engineer',
        source_platform: 'Barclays Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Product Manager - FinTech',
        company: 'Revolut',
        location: 'London, United Kingdom',
        job_type: 'Full-time',
        salary_range: '£65,000 - £95,000',
        description: 'Shape the future of banking at Europe\'s fastest growing fintech. Lead cross-functional teams to deliver innovative financial products.',
        requirements: 'Bachelor\'s degree, 4+ years product management, fintech or financial services experience, data-driven mindset, strong communication skills',
        source_url: 'https://www.revolut.com/careers/product-manager',
        source_platform: 'Revolut Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Senior Accountant',
        company: 'Deloitte UK',
        location: 'Birmingham, United Kingdom',
        job_type: 'Full-time',
        salary_range: '£45,000 - £65,000',
        description: 'Join Deloitte\'s audit practice. Work with leading UK businesses. Skilled Worker visa sponsorship provided.',
        requirements: 'ACCA or ACA qualified, 3+ years audit experience, strong analytical skills, excellent communication, willingness to travel',
        source_url: 'https://jobs.deloitte.co.uk/senior-accountant',
        source_platform: 'Deloitte Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Machine Learning Engineer',
        company: 'DeepMind',
        location: 'London, United Kingdom',
        job_type: 'Full-time',
        salary_range: '£80,000 - £130,000',
        description: 'Push the boundaries of AI research. Work on cutting-edge machine learning systems that solve real-world problems.',
        requirements: 'PhD in Machine Learning, Computer Science, or related field, strong publication record, experience with TensorFlow/PyTorch, Python expertise',
        source_url: 'https://deepmind.google/careers/ml-engineer',
        source_platform: 'DeepMind',
        remote_option: false,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Civil Engineer',
        company: 'Arup',
        location: 'Edinburgh, United Kingdom',
        job_type: 'Full-time',
        salary_range: '£40,000 - £60,000',
        description: 'Work on landmark infrastructure projects across the UK. Visa sponsorship available for experienced engineers.',
        requirements: 'Bachelor\'s or Master\'s in Civil Engineering, Chartered Engineer status or working towards, 3+ years experience, AutoCAD, structural analysis',
        source_url: 'https://www.arup.com/careers/civil-engineer',
        source_platform: 'Arup Careers',
        remote_option: false,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Healthcare Assistant',
        company: 'Bupa UK',
        location: 'Leeds, United Kingdom',
        job_type: 'Full-time',
        salary_range: '£22,000 - £28,000',
        description: 'Provide compassionate care in our care homes. Full training and visa sponsorship for qualified candidates from overseas.',
        requirements: 'Healthcare qualification or relevant experience, caring nature, good communication skills, willingness to work shifts, right to work support provided',
        source_url: 'https://www.bupa.jobs/healthcare-assistant',
        source_platform: 'Bupa Careers',
        remote_option: false,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Backend Engineer',
        company: 'Amazon UK',
        location: 'London, United Kingdom',
        job_type: 'Full-time',
        salary_range: '£65,000 - £95,000',
        description: 'Build scalable backend systems for Amazon\'s retail and AWS platforms. Visa sponsorship and relocation package included.',
        requirements: 'Bachelor\'s in Computer Science, 4+ years backend development, Java or Python, distributed systems, microservices, AWS experience a plus',
        source_url: 'https://www.amazon.jobs/backend-engineer-uk',
        source_platform: 'Amazon Jobs',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },

      // ==================== USA JOBS WITH VISA SPONSORSHIP (H-1B) ====================
      {
        title: 'Software Engineer II',
        company: 'Microsoft',
        location: 'Seattle, Washington, USA',
        job_type: 'Full-time',
        salary_range: '$120,000 - $180,000',
        description: 'Join Microsoft to build products that empower every person on the planet. H-1B visa sponsorship available for qualified candidates.',
        requirements: 'Bachelor\'s or Master\'s in Computer Science, 3+ years software development, C++, C#, or Java, cloud experience, strong problem-solving skills',
        source_url: 'https://careers.microsoft.com/software-engineer',
        source_platform: 'Microsoft Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Data Engineer',
        company: 'Meta',
        location: 'Menlo Park, California, USA',
        job_type: 'Full-time',
        salary_range: '$140,000 - $200,000',
        description: 'Build data pipelines that power Facebook, Instagram, and WhatsApp. We sponsor H-1B visas for exceptional talent.',
        requirements: 'Bachelor\'s or Master\'s in Computer Science, 4+ years data engineering, Python, SQL, Spark, Hadoop, ETL experience',
        source_url: 'https://www.metacareers.com/data-engineer',
        source_platform: 'Meta Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Senior Product Manager',
        company: 'Apple',
        location: 'Cupertino, California, USA',
        job_type: 'Full-time',
        salary_range: '$150,000 - $220,000',
        description: 'Lead product development for groundbreaking Apple products. Visa sponsorship and relocation assistance provided.',
        requirements: 'MBA or technical Master\'s degree, 6+ years product management, consumer technology experience, cross-functional leadership',
        source_url: 'https://jobs.apple.com/senior-product-manager',
        source_platform: 'Apple Jobs',
        remote_option: false,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Machine Learning Scientist',
        company: 'OpenAI',
        location: 'San Francisco, California, USA',
        job_type: 'Full-time',
        salary_range: '$180,000 - $300,000',
        description: 'Shape the future of AI at OpenAI. Work on large language models and frontier AI research. Full visa sponsorship.',
        requirements: 'PhD in Machine Learning, AI, or related field, strong publication record, PyTorch/TensorFlow, NLP or computer vision expertise',
        source_url: 'https://openai.com/careers/ml-scientist',
        source_platform: 'OpenAI Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Full Stack Engineer',
        company: 'Stripe',
        location: 'San Francisco, California, USA',
        job_type: 'Full-time',
        salary_range: '$130,000 - $190,000',
        description: 'Build the economic infrastructure for the internet. H-1B sponsorship and comprehensive relocation support.',
        requirements: 'Bachelor\'s in Computer Science, 4+ years full stack development, React, Node.js, Ruby, PostgreSQL, payments experience a plus',
        source_url: 'https://stripe.com/jobs/full-stack-engineer',
        source_platform: 'Stripe Jobs',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Research Scientist - AI',
        company: 'NVIDIA',
        location: 'Santa Clara, California, USA',
        job_type: 'Full-time',
        salary_range: '$160,000 - $250,000',
        description: 'Advance the state of AI hardware and software at NVIDIA. Visa sponsorship for exceptional researchers.',
        requirements: 'PhD in Computer Science, Machine Learning, or related field, CUDA experience, deep learning frameworks, GPU programming',
        source_url: 'https://nvidia.wd5.myworkdayjobs.com/research-scientist',
        source_platform: 'NVIDIA Careers',
        remote_option: false,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Cloud Solutions Architect',
        company: 'Salesforce',
        location: 'Austin, Texas, USA',
        job_type: 'Full-time',
        salary_range: '$130,000 - $180,000',
        description: 'Design enterprise cloud solutions for Fortune 500 companies. H-1B visa sponsorship available.',
        requirements: 'Bachelor\'s degree, 5+ years cloud architecture, Salesforce certifications, AWS/Azure, enterprise solution design',
        source_url: 'https://salesforce.wd1.myworkdayjobs.com/architect',
        source_platform: 'Salesforce Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Registered Nurse - ICU',
        company: 'Cleveland Clinic',
        location: 'Cleveland, Ohio, USA',
        job_type: 'Full-time',
        salary_range: '$65,000 - $90,000',
        description: 'Join one of America\'s top hospitals. EB-3 visa sponsorship and comprehensive relocation for qualified international nurses.',
        requirements: 'BSN degree, RN license (or eligibility), 2+ years ICU experience, NCLEX-RN passed or eligible, English proficiency',
        source_url: 'https://jobs.clevelandclinic.org/icu-nurse',
        source_platform: 'Cleveland Clinic Jobs',
        remote_option: false,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Financial Analyst',
        company: 'Goldman Sachs',
        location: 'New York, New York, USA',
        job_type: 'Full-time',
        salary_range: '$100,000 - $150,000',
        description: 'Join our Investment Banking division. H-1B visa sponsorship for exceptional candidates.',
        requirements: 'Bachelor\'s or MBA in Finance, Economics, 2+ years financial analysis, Excel modeling, financial statement analysis',
        source_url: 'https://www.goldmansachs.com/careers/financial-analyst',
        source_platform: 'Goldman Sachs Careers',
        remote_option: false,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'iOS Developer',
        company: 'Uber',
        location: 'San Francisco, California, USA',
        job_type: 'Full-time',
        salary_range: '$130,000 - $185,000',
        description: 'Build the Uber app used by millions daily. Comprehensive visa sponsorship and relocation package.',
        requirements: 'Bachelor\'s in Computer Science, 3+ years iOS development, Swift, UIKit/SwiftUI, mobile architecture patterns',
        source_url: 'https://www.uber.com/careers/ios-developer',
        source_platform: 'Uber Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },

      // ==================== CANADA JOBS WITH VISA SPONSORSHIP ====================
      {
        title: 'Senior Software Developer',
        company: 'Shopify',
        location: 'Toronto, Ontario, Canada',
        job_type: 'Full-time',
        salary_range: 'CAD 120,000 - 170,000',
        description: 'Build commerce solutions that power millions of businesses. LMIA-supported work permit sponsorship available.',
        requirements: 'Bachelor\'s in Computer Science, 5+ years software development, Ruby, React, GraphQL, e-commerce experience',
        source_url: 'https://www.shopify.com/careers/senior-developer',
        source_platform: 'Shopify Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Data Scientist',
        company: 'RBC (Royal Bank of Canada)',
        location: 'Toronto, Ontario, Canada',
        job_type: 'Full-time',
        salary_range: 'CAD 90,000 - 130,000',
        description: 'Apply machine learning to banking at Canada\'s largest bank. Work permit sponsorship and relocation support.',
        requirements: 'Master\'s or PhD in Data Science, Statistics, 3+ years experience, Python, R, SQL, machine learning, financial modeling',
        source_url: 'https://jobs.rbc.com/data-scientist',
        source_platform: 'RBC Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Registered Nurse',
        company: 'Vancouver Coastal Health',
        location: 'Vancouver, British Columbia, Canada',
        job_type: 'Full-time',
        salary_range: 'CAD 70,000 - 95,000',
        description: 'Join BC\'s healthcare system. Immigration support and relocation assistance for qualified international nurses.',
        requirements: 'Nursing degree, NNAS assessment, NCLEX-RN, English proficiency (IELTS/CELBAN), 2+ years clinical experience',
        source_url: 'https://careers.vch.ca/registered-nurse',
        source_platform: 'VCH Careers',
        remote_option: false,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'DevOps Engineer',
        company: 'Hootsuite',
        location: 'Vancouver, British Columbia, Canada',
        job_type: 'Full-time',
        salary_range: 'CAD 100,000 - 140,000',
        description: 'Build and scale cloud infrastructure for social media management platform. Visa sponsorship available.',
        requirements: 'Bachelor\'s in Computer Science, 4+ years DevOps, AWS/GCP, Kubernetes, Docker, Terraform, CI/CD',
        source_url: 'https://careers.hootsuite.com/devops-engineer',
        source_platform: 'Hootsuite Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Machine Learning Engineer',
        company: 'Cohere',
        location: 'Toronto, Ontario, Canada',
        job_type: 'Full-time',
        salary_range: 'CAD 140,000 - 200,000',
        description: 'Build enterprise AI solutions at one of Canada\'s leading AI companies. Full visa sponsorship.',
        requirements: 'Master\'s or PhD in Machine Learning, NLP experience, PyTorch/TensorFlow, large language models, Python',
        source_url: 'https://cohere.com/careers/ml-engineer',
        source_platform: 'Cohere Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Financial Analyst',
        company: 'TD Bank',
        location: 'Toronto, Ontario, Canada',
        job_type: 'Full-time',
        salary_range: 'CAD 70,000 - 95,000',
        description: 'Join TD\'s finance team. LMIA support for qualified international candidates.',
        requirements: 'Bachelor\'s in Finance or Accounting, CFA/CPA in progress, 2+ years financial analysis, Excel, financial modeling',
        source_url: 'https://jobs.td.com/financial-analyst',
        source_platform: 'TD Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Mining Engineer',
        company: 'Teck Resources',
        location: 'Calgary, Alberta, Canada',
        job_type: 'Full-time',
        salary_range: 'CAD 95,000 - 130,000',
        description: 'Work on major mining operations. Visa sponsorship and fly-in/fly-out options available.',
        requirements: 'Bachelor\'s in Mining Engineering, Professional Engineer designation (or eligibility), 3+ years mining experience',
        source_url: 'https://www.teck.com/careers/mining-engineer',
        source_platform: 'Teck Careers',
        remote_option: false,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Product Manager',
        company: 'Wealthsimple',
        location: 'Toronto, Ontario, Canada',
        job_type: 'Full-time',
        salary_range: 'CAD 110,000 - 150,000',
        description: 'Shape the future of investing for Canadians. Work permit sponsorship for exceptional candidates.',
        requirements: 'Bachelor\'s degree, 4+ years product management, fintech experience, data-driven decision making, agile methodologies',
        source_url: 'https://www.wealthsimple.com/careers/product-manager',
        source_platform: 'Wealthsimple Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Civil Engineer',
        company: 'SNC-Lavalin',
        location: 'Montreal, Quebec, Canada',
        job_type: 'Full-time',
        salary_range: 'CAD 80,000 - 110,000',
        description: 'Work on infrastructure projects across Canada. Immigration support for qualified engineers.',
        requirements: 'Bachelor\'s in Civil Engineering, P.Eng eligibility, 4+ years experience, AutoCAD, structural design',
        source_url: 'https://www.snclavalin.com/careers/civil-engineer',
        source_platform: 'SNC-Lavalin Careers',
        remote_option: false,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'UX Designer',
        company: 'Shopify',
        location: 'Ottawa, Ontario, Canada',
        job_type: 'Full-time',
        salary_range: 'CAD 90,000 - 130,000',
        description: 'Design intuitive e-commerce experiences. LMIA-supported work permit for international talent.',
        requirements: 'Bachelor\'s in Design, HCI, 4+ years UX design, Figma, user research, design systems, strong portfolio',
        source_url: 'https://www.shopify.com/careers/ux-designer',
        source_platform: 'Shopify Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },

      // ==================== AUSTRALIA JOBS WITH VISA SPONSORSHIP ====================
      {
        title: 'Software Engineer',
        company: 'Atlassian',
        location: 'Sydney, New South Wales, Australia',
        job_type: 'Full-time',
        salary_range: 'AUD 120,000 - 170,000',
        description: 'Build collaboration tools used by millions. 482 visa sponsorship for skilled engineers.',
        requirements: 'Bachelor\'s in Computer Science, 4+ years software development, Java, Python, or JavaScript, distributed systems',
        source_url: 'https://www.atlassian.com/careers/software-engineer',
        source_platform: 'Atlassian Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Data Analyst',
        company: 'Commonwealth Bank',
        location: 'Sydney, New South Wales, Australia',
        job_type: 'Full-time',
        salary_range: 'AUD 85,000 - 115,000',
        description: 'Drive data-driven decisions at Australia\'s largest bank. Skilled visa sponsorship available.',
        requirements: 'Bachelor\'s in Statistics, Data Science, or related field, 3+ years data analysis, SQL, Python, Tableau/Power BI',
        source_url: 'https://www.commbank.com.au/careers/data-analyst',
        source_platform: 'CommBank Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Registered Nurse',
        company: 'NSW Health',
        location: 'Sydney, New South Wales, Australia',
        job_type: 'Full-time',
        salary_range: 'AUD 70,000 - 95,000',
        description: 'Join the NSW public health system. 482/494 visa sponsorship and relocation assistance for international nurses.',
        requirements: 'Nursing degree, AHPRA registration (or eligibility), IELTS 7.0+, 2+ years clinical experience',
        source_url: 'https://jobs.health.nsw.gov.au/registered-nurse',
        source_platform: 'NSW Health Jobs',
        remote_option: false,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Mining Engineer',
        company: 'BHP',
        location: 'Perth, Western Australia, Australia',
        job_type: 'Full-time',
        salary_range: 'AUD 130,000 - 180,000',
        description: 'Work on world-class mining operations. 482 visa sponsorship and FIFO options available.',
        requirements: 'Bachelor\'s in Mining Engineering, 5+ years experience, operational mining knowledge, safety management',
        source_url: 'https://www.bhp.com/careers/mining-engineer',
        source_platform: 'BHP Careers',
        remote_option: false,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Cloud Engineer',
        company: 'Canva',
        location: 'Sydney, New South Wales, Australia',
        job_type: 'Full-time',
        salary_range: 'AUD 140,000 - 190,000',
        description: 'Scale infrastructure for 100M+ users. Visa sponsorship and comprehensive relocation package.',
        requirements: 'Bachelor\'s in Computer Science, 5+ years cloud engineering, AWS/GCP, Kubernetes, Terraform, Python',
        source_url: 'https://www.canva.com/careers/cloud-engineer',
        source_platform: 'Canva Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Accountant',
        company: 'KPMG Australia',
        location: 'Melbourne, Victoria, Australia',
        job_type: 'Full-time',
        salary_range: 'AUD 75,000 - 100,000',
        description: 'Join KPMG\'s audit and assurance practice. 482 skilled visa sponsorship for qualified accountants.',
        requirements: 'Bachelor\'s in Accounting, CA/CPA qualified, 3+ years audit experience, strong analytical skills',
        source_url: 'https://www.kpmg.com.au/careers/accountant',
        source_platform: 'KPMG Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Geologist',
        company: 'Rio Tinto',
        location: 'Brisbane, Queensland, Australia',
        job_type: 'Full-time',
        salary_range: 'AUD 110,000 - 150,000',
        description: 'Explore and develop mineral resources. Visa sponsorship for experienced geologists.',
        requirements: 'Bachelor\'s or Master\'s in Geology, 4+ years mining geology experience, GIS, exploration methodologies',
        source_url: 'https://www.riotinto.com/careers/geologist',
        source_platform: 'Rio Tinto Careers',
        remote_option: false,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Product Designer',
        company: 'Atlassian',
        location: 'Sydney, New South Wales, Australia',
        job_type: 'Full-time',
        salary_range: 'AUD 110,000 - 150,000',
        description: 'Design collaboration experiences for teams worldwide. Skilled visa sponsorship available.',
        requirements: 'Bachelor\'s in Design, 5+ years product design, Figma, user research, design systems, strong portfolio',
        source_url: 'https://www.atlassian.com/careers/product-designer',
        source_platform: 'Atlassian Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Mechanical Engineer',
        company: 'Woodside Energy',
        location: 'Perth, Western Australia, Australia',
        job_type: 'Full-time',
        salary_range: 'AUD 120,000 - 160,000',
        description: 'Work on major energy projects. 482/494 visa sponsorship for qualified engineers.',
        requirements: 'Bachelor\'s in Mechanical Engineering, 5+ years oil & gas experience, equipment design, project management',
        source_url: 'https://www.woodside.com.au/careers/mechanical-engineer',
        source_platform: 'Woodside Careers',
        remote_option: false,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        title: 'Backend Developer',
        company: 'Afterpay',
        location: 'Melbourne, Victoria, Australia',
        job_type: 'Full-time',
        salary_range: 'AUD 115,000 - 155,000',
        description: 'Build payment infrastructure at scale. Comprehensive visa sponsorship and relocation.',
        requirements: 'Bachelor\'s in Computer Science, 4+ years backend development, Java or Python, microservices, payments experience a plus',
        source_url: 'https://www.afterpay.com/careers/backend-developer',
        source_platform: 'Afterpay Careers',
        remote_option: true,
        visa_sponsorship: true,
        posted_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ];

    let newJobs = 0;
    let duplicates = 0;

    for (const job of sampleJobs) {
      // Check for existing job
      const { data: existingJob } = await supabaseClient
        .from('jobs')
        .select('id')
        .eq('title', job.title)
        .eq('company', job.company)
        .eq('location', job.location)
        .maybeSingle();

      if (existingJob) {
        console.log(`Duplicate found: ${job.title} at ${job.company}`);
        duplicates++;
        continue;
      }

      // Insert new job
      const { error: insertError } = await supabaseClient
        .from('jobs')
        .insert({
          ...job,
          is_active: true,
        });

      if (insertError) {
        console.error(`Error inserting job: ${insertError.message}`);
      } else {
        newJobs++;
        console.log(`Inserted: ${job.title} at ${job.company}`);
      }
    }

    console.log(`Scraping complete. New jobs: ${newJobs}, Duplicates: ${duplicates}`);

    return new Response(
      JSON.stringify({ 
        success: true, 
        newJobs, 
        duplicates,
        message: `Added ${newJobs} new jobs (${duplicates} duplicates skipped)` 
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in scrape-jobs:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});